### ISSUE TITLE
Convert into a DataLad extension?

### ISSUE THREAD

**Issue by mih** [rciric/datalad-osf-utils#5]
Thanks for developing this package! With relatively minimal effort, it could be turned into a proper DataLad extension http://docs.datalad.org/en/latest/customization.html#extension-packages

It would then expose regular datalad commands (Python and cmdline API), and fully integrate with an existing datalad installation on a system.

If you are interested in that I would aim to compose a draft PR with the key ingredients that could then be tuned to match expectations.

Here are a few existing extensions: http://docs.datalad.org/en/latest/index.html#extension-packages

How do you feel about this?

**Comment by sappelhoff** [comment]
Just to support this as a user: I think this is a cool idea. @rciric

**Comment by sappelhoff** [comment]
see also: https://github.com/ohbm/hackathon2020/issues/156
